apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b8tzeeacu-java-quarkus
  janus-idp.io/tekton: b8tzeeacu-java-quarkus
  backstage.io/kubernetes-id: b8tzeeacu-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b8tzeeacu-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
